### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by fullofcaffeine** [mengwong/org-asana#4]
I'm a long time user of orgmode, but also use Asana for collaboration. This looks like a great way to integrate both. I'm wondering what's the status of this project? Is it abandoned or is it stable enough you didn't need to further develop it?

Cheers and thanks for sharing!

**Comment by mengwong** [comment]
apologies … the project is pretty much abandoned due to other commitments. If anyone would like to take over that would be cool.

**Comment by mengwong** [comment]
a lot of the basic plumbing is functional but the synchronization is not there.
